### ISSUE TITLE
raw serializer returns no value prop on keys created without quotation marks

### ISSUE THREAD

**Issue by akuzia** [api7/lua-resty-etcd#105]
`etcdv3:get` method table has no value prop. on keys created without double quotation marks:

```
> etcdctl put /foo/baz bar
OK
> etcdctl get /foo/baz    
/foo/baz
bar
```

```
content_by_lua_block {
    local etcd = require "resty.etcd"
    local cjson = require "cjson.safe"
    local json_encode = cjson.encode

    local conn, err = etcd.new({
        protocol = "v3",
        http_host = {
            "http://etcd1:2379",
            "http://etcd2:2379",
            "http://etcd3:2379",
        },
        serializer = "raw"
    })

    res, err = conn:get("/foo/baz")

    ngx.say(json_encode(res.body.kvs[1]))
}
```

`{"version":"1","key":"\/foo\/baz","mod_revision":"19","create_revision":"19"}`

But if you create key with double quotes:
```
> etcdctl put /foo/baz \"bar\"
OK
> etcdctl get /foo/baz
/foo/baz
"bar"
```
`{"version":"3","key":"\/foo\/baz","create_revision":"19","mod_revision":"24","value":"bar"}`

etcdv3:set method predictably puts values with quotation marks

**Comment by membphis** [comment]
@nic-chen @Yiyiyimu do you have time to look at this issue?

**Comment by Gerrard-YNWA** [comment]
Hello, as far as I konwn， `serializer` option was not implemented yet in v3 api.

**Comment by nic-chen** [comment]
yes, we only support json format now, PR is welcome.

**Comment by akuzia** [comment]
Json serializer behaves the same way in my testing

**Comment by membphis** [comment]
> Hello, as far as I know， `serializer` option was not implemented yet in v3 api.

please confirm, @nic-chen

**Comment by Gerrard-YNWA** [comment]
@akuzia because default `cjson.encode` trims the double quote.

I just submit a patch https://github.com/Gerrard-YNWA/lua-resty-etcd/tree/feat/v3-serializer-opt to support raw serializer option, but currently the test was not covered, will add some test case later and send a pr. 

If you need this feature, you can try this patch ahead.

**Comment by membphis** [comment]
@Gerrard-YNWA help you to submit a PR right now(draft status). you can add the test case later

**Comment by Gerrard-YNWA** [comment]
@akuzia patch has been merged https://github.com/api7/lua-resty-etcd/pull/106, hope it can help you.
