### ISSUE TITLE
Bug: when no endpoints is healthy, "it will cause crazy retries"

### ISSUE THREAD

**Issue by Yiyiyimu** [api7/lua-resty-etcd#111]
#109 fixed the situation when some endpoints got taints it could be jumped over. But when all endpoints are unhealthy, it keeps the old method, so the problem of #101 still not fixed and "it will cause crazy retries". See [discussion](https://github.com/api7/lua-resty-etcd/pull/109#discussion_r560273225)

**Comment by Yiyiyimu** [comment]
ping @tzssangglass @nic-chen @membphis

**Comment by membphis** [comment]
I added a `bug`, let us fix it

**Comment by tzssangglass** [comment]
so we stop requesting etcd  when all endpoints are unhealthy?

**Comment by nic-chen** [comment]
How about increasing the waiting time?

**Comment by tzssangglass** [comment]
> How about increasing the waiting time?

ngx.sleep?

**Comment by membphis** [comment]
It is more reasonable for the caller to add processing logic.

**Comment by tzssangglass** [comment]
provide some processing strategies for caller to choose from?

- stop requesting etcd(default)
- ngx.sleep
- keeps the old method

**Comment by tzssangglass** [comment]
> It is more reasonable for the caller to add processing logic.

are you saying let the caller write the code themselves and have `healthcheck` call it?

**Comment by membphis** [comment]
When there is no healthy node available, we can directly return an error message.
The caller decides how long to sleep based on the return error message.

**Comment by tzssangglass** [comment]
> When there is no healthy node available, we can directly return an error message.
> The caller decides how long to sleep based on the return error message.

agree +1

**Comment by membphis** [comment]
we can check the process way in APISIX ^_^

**Comment by tzssangglass** [comment]
assigned me, fix later
