### ISSUE TITLE
Request help: new release to support etcd health-check

### ISSUE THREAD

**Issue by Yiyiyimu** [api7/lua-resty-etcd#115]
Hi @membphis I think we could release a new version

**Comment by membphis** [comment]
would you like to submit a PR? 

for example: https://github.com/api7/lua-resty-etcd/commit/804a6a61cb1721945ff45d740a7fdcf76db6c876

**Comment by Yiyiyimu** [comment]
No problem got it

**Comment by Yiyiyimu** [comment]
No problem got it

**Comment by membphis** [comment]
merged https://github.com/api7/lua-resty-etcd/pull/116
