### ISSUE TITLE
etcd v3 set timeout to 0 causing  "can't resume a dead coroutine"

### ISSUE THREAD

**Issue by findmark** [api7/lua-resty-etcd#118]
Hi there, when I use watch feature with etcd v3, unexpected error occurred when setting timeout to 0, which I need to keep watching the peers, any idea what I was missing?

my code
`
   local func, err = _M.etcd:watch(key, {
        timeout = 0 -- forever watch
    })
`

log info
`
2021/02/04 12:08:50 [info] 10188#12103689: *5 [lua] v3.lua:518: request_chunk(): http request meth
od: POST path: /v3/watch body: {"create_request":{"key":"c2VydmVy"}} query: nil, context: ngx.time
r
2021/02/04 12:09:00 [error] 10188#12103689: *5 [lua] monitor.lua:28: watch_server(): timeout, context: ngx.timer
2021/02/04 12:09:00 [error] 10188#12103689: *5 lua coroutine: runtime error: .../local/Cellar/openresty/1.15.8.3_1/lualib/resty/http.lua:409: bad argument #1 to 'tonumber' (string expected, got nil)
stack traceback:
coroutine 0:
        [C]: in function 'tonumber'
        .../local/Cellar/openresty/1.15.8.3_1/lualib/resty/http.lua:409: in function <.../local/Cellar/openresty/1.15.8.3_1/lualib/resty/http.lua:383>
coroutine 1:
        [C]: in function 'co_resume'
        .../local/Cellar/openresty/1.15.8.3_1/lualib/resty/http.lua:80: in function 'body_reader'
        ...cuments/projects/openresty//lua/vendor/resty/etcd/v3.lua:533: in function 'func'
        ...ents/projects/openresty//lua/goatkeeper/etcd/monitor.lua:25: in function 'watch_server'
        ...ents/projects/openresty//lua/goatkeeper/etcd/monitor.lua:84: in function 'watch_config'
        ...ments/projects/openresty//lua/goatkeeper/etcd/syncer.lua:66: in function <...ments/projects/openresty//lua/goatkeeper/etcd/syncer.lua:56>, context: ngx.timer
2021/02/04 12:09:00 [error] 10188#12103689: *5 [lua] monitor.lua:28: watch_server(): failed to dec
ode json body: Expected value but found invalid token at character 1, context: ngx.timer
2021/02/04 12:09:00 [error] 10188#12103689: *5 [lua] monitor.lua:28: watch_server(): can't resume
a dead coroutine, context: ngx.timer
2021/02/04 12:09:00 [error] 10188#12103689: *5 [lua] monitor.lua:28: watch_server(): can't resume
a dead coroutine, context: ngx.timer
2021/02/04 12:09:00 [error] 10188#12103689: *5 [lua] monitor.lua:28: watch_server(): can't resume
a dead coroutine, context: ngx.timer
`

**Comment by membphis** [comment]
@Yiyiyimu do you have time to look at this issue?

**Comment by Yiyiyimu** [comment]
> do you have time to look at this issue?

Working on it.

**Comment by Yiyiyimu** [comment]
Hi @findmark, it seems I could not reproduce the error. Could you provide a minimum reproduce steps and environment? Or you could try mine, change the timeout in the test and see if it works.

BTW, it seems we could not set `timeout = 0` to get forever watch, it would turn to use the default `lua_socket_connect_timeout` when we do `tcpsock:settimeout(0)`. You could get that from openresty [test case](https://github.com/openresty/lua-nginx-module/blob/master/t/023-rewrite/tcp-socket-timeout.t#L141-L173). Maybe you could try to set timeout to a large enough value.

**Comment by findmark** [comment]
hi @Yiyiyimu , sorry for the delay, actually I already figured out the issue yesterday.
In general, it happens because the [document](https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md) here says set to 0 to disable timeout. So I assumed set to 0 can forever watch the etcd key changes. But turn out it will timeout after 10s, maybe is the default timeout settings, not sure yet. Therefore, set to 0 does not take effect, or I mistaken the meaning of that.
And the reason there are so many "can't resume a dead coroutine" error messages is just because I had removed break when the callback function returns err.
You can feel free to close the issue now, and I suggest to adjust the document or demonstrate more detail about "timeout (int) request timeout seconds. set 0 to disable timeout.", so it will not confuse people like me.
Again, thanks for your kindly help and @membphis kindness.
BTW, I am also interesting in Api gateway, currently working on api gateway project in our compony, is there a WeChat group chat for api gateway? If it is, do I have privileges to join in?

**Comment by Yiyiyimu** [comment]
Hi @findmark! Glad you fix it! Sorry for the document error, thanks for the remind and I'll fix it later.

I'm in APISIX wechat group, if by any chances you're interested in Apache APISIX, you could send me your wechat ID through email and I'll get you in. Also you could find other APISIX Community like [QQ group/Slack/Mailing List](https://github.com/apache/apisix#community)

**Comment by findmark** [comment]
Thanks for the advice, i will checkout apisix first! Nice meeting you and happy new year in advance!

**Comment by Yiyiyimu** [comment]
@findmark Happy new year~
