### ISSUE TITLE
If a node in the ETCD cluster dies, it cannot be accessed properly

### ISSUE THREAD

**Issue by GBXing** [api7/lua-resty-etcd#121]
If you configure 3 nodes of ETCD in the configuration file, as long as one node dies, the access to ETCD will be wrong. Can resty.etcd determine whether the node is healthy or not?

**Comment by spacewander** [comment]
I saw you have submitted the same issue to APISIX: https://github.com/apache/apisix/issues/3673

Close as duplicated.
