### ISSUE TITLE
I think there is something wrong with CI.

### ISSUE THREAD

**Issue by wfnuser** [api7/lua-resty-etcd#140]
https://github.com/api7/lua-resty-etcd/pull/107 
In this pull request, the ci failed at first. After I just rebase the code to master, the ci had been passed.
I think we should run CI after merge the code automatically? What do you say?
Otherwise, even the CI passed, you can not sure after merge the CI will pass.

**Comment by Yiyiyimu** [comment]
Hi @wfnuser I think it got fixed in #120

**Comment by wfnuser** [comment]
Aha... Let me search about what fail fast done.

**Comment by wfnuser** [comment]
So it doesn't work in my pull request. Is just because the CI config file wasn't updated yet?

**Comment by Yiyiyimu** [comment]
Since #107 is submitted before #120, I guess the need for merge master to make the fix in #120 work is expected

**Comment by wfnuser** [comment]
Cool.
