### ISSUE TITLE
feature: there may be a lot of routes, need to support paging queries.

### ISSUE THREAD

**Issue by membphis** [api7/lua-resty-etcd#15]
this feature maybe depend on: https://github.com/iresty/lua-resty-etcd/issues/5

**Comment by Yiyiyimu** [comment]
Hi @membphis is this still a problem need to fix?

**Comment by moonming** [comment]
yes, I think it still a problem

**Comment by Yiyiyimu** [comment]
Thank you @moonming I'll try to work on this one

**Comment by membphis** [comment]
@nic-chen Does the API implementation of the v3 version support paging now?

**Comment by Yiyiyimu** [comment]
@membphis the option "limit" would do the pagination and yes it has already been implemented in [readdir](https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md#readdir).

**Comment by membphis** [comment]
many thanks for your reminding @Yiyiyimu

**Comment by Yiyiyimu** [comment]
My pleasure. Thanks for giving me the chance to understand this feature. 

Do we need to close this issue now? @membphis

**Comment by membphis** [comment]
closed
