### ISSUE TITLE
error  "ngx_http_lua_ffi_exec_regex"

### ISSUE THREAD

**Issue by smallbirdwy** [api7/lua-resty-etcd#151]
when i require etct.lua , lua entry thread aborted: runtime error /nginx/lualib/ngx/re.lua:47 missing declaration for symbol 'ngx_http_lua_ffi_exec_regex'

nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 
built with Openssl 1.1.1c

this my install "./configure --prefix=/nginx --with-pcre=/pcre-8.39 --with-openssl=/openssl-1.1.1c --with-zlib=/zlib-1.2.8 --with-http_sub_module"

**Comment by spacewander** [comment]
A known issue in the old version of OpenResty.
Better to upgrade OpenResty 1.19+

**Comment by smallbirdwy** [comment]
thank you
