### ISSUE TITLE
feature: support talking to etcd via TLS.

### ISSUE THREAD

**Issue by membphis** [api7/lua-resty-etcd#17]
The TLS authentication for etcd is usually bidirectional, but cosocket is not supported now, but fortunately, there is currently a PR in progress.

we need to fix this first: openresty/lua-nginx-module#997

related issue: https://github.com/iresty/apisix/issues/158

**Comment by JansonLiao** [comment]
so the lua-resty-etcd still do not support connect to etcd via TLS?

**Comment by membphis** [comment]
we can use `etcd proxy`, it is an easy way.

**Comment by spacewander** [comment]
Solved by #86. Server side TLS verification is enough to use by now.
