### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by membphis** [api7/lua-resty-etcd#43]
https://github.com/iresty/lua-resty-etcd/pull/41#issuecomment-552104393

**Comment by Yiyiyimu** [comment]
Hi @membphis , I'm a bit confused about this one. What kind of code style do you expect us to have

**Comment by moonming** [comment]
This means a line with a maximum of 80 characters. This is not important.

**Comment by Yiyiyimu** [comment]
Sure thank you @moonming ! Do we need to close this issue?

**Comment by moonming** [comment]
yes, we can close it.
