### ISSUE TITLE
etcd client cache is supported ?

### ISSUE THREAD

**Issue by wuchencm** [api7/lua-resty-etcd#51]
etcd client cache is supported ?

**Comment by membphis** [comment]
Can you support more information? I don't understand what you mean.

**Comment by wuchencm** [comment]
Does the client connect etcd with each request ，else get the key-value from cache of client

**Comment by membphis** [comment]
This driver is used to directly manipulate etcd, and the cache should be handed to an external package.

**Comment by wuchencm** [comment]
> This driver is used to directly manipulate etcd, and the cache should be handed to an external package.

Can you provide the  link about etcd cache ？thx

**Comment by membphis** [comment]
https://github.com/apache/incubator-apisix/blob/master/lua/apisix/core/config_etcd.lua

you can take a look at this.

**Comment by wuchencm** [comment]
> https://github.com/apache/incubator-apisix/blob/master/lua/apisix/core/config_etcd.lua
> 
> you can take a look at this.

thx
