### ISSUE TITLE
why only json values 

### ISSUE THREAD

**Issue by Ara4Sh** [api7/lua-resty-etcd#57]
Hello everyone,

I was trying to replace Redis with etcd to keep my configurations between multiple regions but I checked api7 etcd library only supports values in json, why?

**Comment by membphis** [comment]
I personally prefer the json format.
What other formats do you want to support? yaml?

**Comment by membphis** [comment]
Do you mean to allow users to customize the encoding and decoding method of table -> value?

**Comment by akuzia** [comment]
@membphis @Gerrard-YNWA 

Looks like something broke in v3:

`local etcd = require "resty.etcd"

                local conn, err = etcd.new({
                    protocol = "v3",
                    http_host = {
                        "http://etcd1:2379",
                        "http://etcd2:2379",
                        "http://etcd3:2379"
                    }
                })

                if err then
                    return
                end

                res, err = conn:set('/foo/bar', 'baz')

                if err then
                    return
                end

                res, err = conn:get("/foo/bar")

                if err then
                    return
                end

                ngx.say(res.body.kvs[1].value) -- baz

                res, err = conn:get("/foo/baz")

                if err then
                    return
                end

                ngx.say(res.body.kvs[1].value) -- nil, but bar expected`
Using etcdctl:

`etcdctl get --prefix /foo    
/foo/bar
"baz"
/foo/baz
bar`

Looks like raw encoder needs mandatory `"` (doble quotes) before and after string value?

**Comment by membphis** [comment]
@akuzia you can create a new `bug` issue, if this is bug, we can fix it.

I want to close this issue now. because this original issue has been fixed by PR https://github.com/api7/lua-resty-etcd/pull/72

**Comment by akuzia** [comment]
@membphis I wasn't able to determine myself is it a bug or made intentionally. Ok, I'll create new issue now #105
