### ISSUE TITLE
ngx.log(ngx.ERR, "failed to check value, got: ", data.body.kvs[1].value,

### ISSUE THREAD

**Issue by wuchencm** [api7/lua-resty-etcd#63]
ngx.log(ngx.ERR, "failed to check value, got: ", data.body.kvs[1].value,

etcdctl can get the value:

![image](https://user-images.githubusercontent.com/14210543/85943134-9f5ea380-b960-11ea-9905-a4f090860f43.png)

local res, err = cli:get("/offline/999999999999999999999")
for k, v in pairs(res.body.kvs[1]) do
        ngx.say(k , "=", v)
end

create_revision=372 mod_revision=372 key=/offline/999999999999999999999 version=1

**Comment by wuchencm** [comment]
好像它只能get到自己写入的key-value，无法获取其他客户端工具写入的value，使用使用相同的协议版本v3

**Comment by membphis** [comment]
only support `json` encoded value now.

**Comment by wuchencm** [comment]
thx
