### ISSUE TITLE
bug: missing value field and got decode error while value is an empty string 

### ISSUE THREAD

**Issue by Gerrard-YNWA** [api7/lua-resty-etcd#71]
reproduce step
1. set empty string
```
etcdctl set /t/empty ''
```
2. use etcd v2 client get and get body as below 
```
{
    "node":{
        "nodes":[
            {
                "createdIndex":9,
                "key":"/t/empty",
                "modifiedIndex":9
            }
        ],
        "modifiedIndex":9,
        "createdIndex":9,
        "key":"/t",
        "dir":true
    },
    "action":"get"
}
```
also an error log from v2.lua
```
2020/08/11 22:15:44 [error] 8951#0: *2 [lua] v2.lua:274: decode_dir_value(): failed to decode json: Expected value but found T_END at character 1, context: ngx.timer
```
It seems that `decode_dir_value` didn't hand empty string properly.

After dive in the implement of v2.lua, does this lib only support for json string value?

**Comment by membphis** [comment]
> After dive in the implement of v2.lua, does this lib only support for json string value?

only support for JSON string value. sure for this now.
if you want to support the original value, we need to export the options `encode/decode` when creating new `etcd` object.

if you would like this feature, welcome PR ^_^

**Comment by Gerrard-YNWA** [comment]
closed via pr https://github.com/api7/lua-resty-etcd/pull/72
