### ISSUE TITLE
Bug: If value is large, v3:watch will cause `json decode` error

### ISSUE THREAD

**Issue by DoubleSpout** [api7/lua-resty-etcd#74]
If value is large, v3:watch will cause `json decode` error. 

http chunk proctocol like this:
`
[chunk size][\r\n][chunk data][\r\n][chunk size][\r\n][chunk data][\r\n][chunk size = 0][\r\n][\r\n]
`

Raw http chunk package is like:

`
32
{some etcd data}

1             <------(here will cause bug)

64
{some etcd data}

0

`

![image](https://user-images.githubusercontent.com/971370/90238211-20fa8a00-de58-11ea-99a2-4f502925b044.png)
if body is "\n", decode_json will caused error

https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua#L523

I will be fix this bug soon, and get a pull request

**Comment by membphis** [comment]
welcome PR ^_^

**Comment by DoubleSpout** [comment]
[https://github.com/api7/lua-resty-etcd/pull/76](https://github.com/api7/lua-resty-etcd/pull/76)
