### ISSUE TITLE
support complex domain names

### ISSUE THREAD

**Issue by dickens7** [api7/lua-resty-etcd#83]
> https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua#L146-L148

- This regular expression verification does not support complex domain names

example： 

 -  http://gateway-etcd-headless.test.svc.cluster.local:2379

**Comment by membphis** [comment]
welcome PR to fix this issue

**Comment by membphis** [comment]
here is a good way:

https://github.com/ledgetech/lua-resty-http/blob/master/lib/resty/http.lua#L251
