### ISSUE TITLE
mark tag 1.3 is pathological

### ISSUE THREAD

**Issue by tokers** [api7/lua-resty-etcd#88]
Since there is a bug in 1.3 which was fixed now, i think may be we need to mark that tag 1.3 is not safe to use and public the next release.

**Comment by tokers** [comment]
@membphis

**Comment by membphis** [comment]
updated. thx.

do you think we need to release a new version 1.4 now?

**Comment by membphis** [comment]
and I have release v1.4 right now. please make a try ^_^
